services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env

  frontend-react:
    build: ./frontend-react
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend-react:/app
      - /app/node_modules
    env_file:
      - .env

volumes:
  backend:
  frontend-react:
