services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - .env

  frontend-nuxt:
    build: ./frontend-nuxt
    ports:
      - "3001:3001"
    volumes:
      - ./frontend-nuxt:/app
      - /app/node_modules
    env_file:
      - .env

volumes:
  backend:
  frontend-nuxt: