services:
  # backend:
  #   build: ./backend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./backend:/app
  #     - /app/node_modules
  #   env_file:
  #     - .env

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env

  # frontend-nuxt:
  #   build: ./frontend-nuxt
  #   ports:
  #     - "3001:3001"
  #   volumes:
  #     - ./frontend-nuxt:/app
  #     - /app/node_modules
  #   env_file:
  #     - .env

  frontend-react:
    build: ./frontend-react
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend-react:/app
      - /app/node_modules
    env_file:
      - .env

volumes:
  backend: # frontend-nuxt:

  frontend-react:
