services:
  backend:
    build:
      context: ./backend
      args:
        AIRTABLE_KEY: $AIRTABLE_KEY
        AIRTABLE_BDD: $AIRTABLE_BDD
        AIRTABLE_TECHNO: $AIRTABLE_TECHNO
        AIRTABLE_PROMO: $AIRTABLE_PROMO
        AIRTABLE_CATEGORIE: $AIRTABLE_CATEGORIE
        AIRTABLE_ETUDIANT: $AIRTABLE_ETUDIANT
        AIRTABLE_ADMIN: $AIRTABLE_ADMIN
        AIRTABLE_PROJET: $AIRTABLE_PROJET
        AIRTABLE_COMMENT: $AIRTABLE_COMMENT
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - .env